I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapters/ch5.rpy", line 184, in script
    show bridge sunset behind shadow with dissolve(1.0)
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapters/ch5.rpy", line 184, in script
    show bridge sunset behind shadow with dissolve(1.0)
  File "C:\Users\vyana\OneDrive\Documents\renpy\renpy-7.4.4-sdk\renpy\ast.py", line 1658, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "C:\Users\vyana\OneDrive\Documents\renpy\renpy-7.4.4-sdk\renpy\exports.py", line 1653, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\vyana\OneDrive\Documents\renpy\renpy-7.4.4-sdk\renpy\display\core.py", line 2798, in do_with
    return self.interact(trans_pause=True,
  File "C:\Users\vyana\OneDrive\Documents\renpy\renpy-7.4.4-sdk\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs) # type: ignore
  File "C:\Users\vyana\OneDrive\Documents\renpy\renpy-7.4.4-sdk\renpy\display\core.py", line 3741, in interact_core
    trans = self.ongoing_transition[None](
TypeError: 'Dissolve' object is not callable

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.1.22070801
Dusk and Dawn 1.0
Sun Aug  7 16:18:46 2022
